<a href="https://colab.research.google.com/github/mithun-martin/AIML-Workshop/blob/main/DAY2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#KERAS BASICS

In [ ]:
#TYPE OF APIS
#1.SEQUENTIAL API = MODEL IS CREATED LAYER BY LAYER
#2.FUNCTIONAL API = MODEL IS CREATED ALL AT ONCE


In [ ]:
#MODEL BUILDING STEPS IN KERAS
#1.GATHER DATA
#2.CREATING NN ARCHITECTURE USING SEQUENTIAL API:
        #INPUT
        #HIDDEN = INPUT SHAPE,ACTIVATION FUNCTION
        #OUTPUT = ACTIVATION FUNCTION
#3.COMPILE:here we define the LOSS FUNCTIONS,OPTIMIZERS,METRICS
#4.FIT THE MODEL = TRAINING

In [ ]:
#ACTIVATION FUNCTION WE USE INSIDE REGRESSION AND CLASSIFICATION
#details given in day2 notes

In [ ]:
# Activation Functions
# Regression
# Hidden Layers : ReLU(preferred choice), LeakyReLU, tanh
# Output Layer : Linear Activation(No Activation Function)

# Classification
# -Binary Classification
# Hidden Layers : ReLU(preferred choice), LeakyReLU, tanh
# Output Layer : Sigmoid

# -Multi-Class Classification
# Hidden Layers : ReLU(preferred choice), LeakyReLU, tanh
# Output Layer : Softmax

In [ ]:
# ReLU(Rectified Linear Unit)
# Formula : f(x) = max(0,x)
# When to use: Default choice for most hidden layers

# Leaky ReLU
# Formula : f(x) = max(ax,x) (where a is a small constant, usually 0.01)
# When to use: If you find ReLU causing too many dead neurons, try Leaky ReLU

# Tanh(Hyperbolic Tangent)
# Formula : f(x) = tanh(x) = (e^x - e^(-x)) / (e^x + e^(-x))
# When to use: In shallow networks or when you need outputs between -1 and 1

# Sigmoid
# Formula : f(x) = 1 / (1 + e^(-x))
# When to use: When you're dealing with two classes (eg: yes/no, true/false, positive/negative, etc.)

# Softmax
# Formula : f(x_i) = e^(x_i) / Σe^(x_j) (for each class i)
# When to use: For multi-class classification problems (eg: classifying digits 0-9)

In [ ]:
#error finding
#MSE,MAE,BINARY CROSS ENTROPY

In [ ]:
import numpy as np
y_acual = ([1000,2000,3000])
#after pred and gng trhroug many algos
y_pred = ([1100,1950,3000])

In [ ]:
error = np.subtract(y_acual,y_pred)
error

array([-100,   50,    0])

In [ ]:
sq_error = np.square(error)
sq_error

array([10000,  2500,     0])

In [ ]:
np.mean(sq_error)

4166.666666666667

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
np.mean(np.absolute(np.subtract(y_acual,y_pred)))


50.0

In [ ]:
mean_squared_error(y_acual,y_pred)


4166.666666666667

In [ ]:
mean_absolute_error(y_acual,y_pred)

50.0

In [ ]:
#BCE
p = [1,1,1,1,0,0,0,0] #actual values

In [ ]:
q = [0.8,0.75,0.7,0.5,0.3,0.3,0.2,.1] #predicted values


In [ ]:
from math import log
def binary_ce(p,q):
       return -((p * log(q)) + ((1 - p) * log(1 - q)))


In [ ]:
result = []
for i in range(len(p)):
    ce = binary_ce(p[i], q[i])
    result.append(ce)

mean_ce = np.mean(result)
mean_ce


0.32531271288927116

In [ ]:
#gmg 2 work with keras now

In [ ]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import RMSprop




In [ ]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
# gng 2 load dataset mnist and stoering in train test forat

In [ ]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()


In [ ]:
x_train.shape,y_train.shape,x_test.shape

((60000, 28, 28), (60000,), (10000, 28, 28))

In [ ]:
#60k images for us to train the model

In [ ]:
#10k images for evaluating the model....we have 784 pixels in 1 image for this dataset that ehy shows 28X28

In [ ]:
x_train[1]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,  51, 159, 253, 159,  50,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,  48, 238, 252, 252, 252, 237,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         54, 227, 253, 252, 239, 233, 252,  57,   6,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  10,  60,
        224, 252, 253, 252, 202,  84, 252, 253, 122,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 163, 252,
        252, 252, 253, 252, 252,  96, 189, 253, 167,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  51, 238, 253,
        253, 190, 114, 253, 228,  47,  79, 255, 168,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,  48, 238, 252, 252,
        179,  12,  75, 121,  21,   0,   0, 253, 243,  50,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,  38, 165, 253, 233, 208,
         84,   0,   0,   0,   0,   0,   0, 253, 252, 165,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   7, 178, 252, 240,  71,  19,
         28,   0,   0,   0,   0,   0,   0, 253, 252, 195,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  57, 252, 252,  63,   0,   0,
          0,   0,   0,   0,   0,   0,   0, 253, 252, 195,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0, 198, 253, 190,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0, 255, 253, 196,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  76, 246, 252, 112,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0, 253, 252, 148,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  85, 252, 230,  25,   0,   0,   0,
          0,   0,   0,   0,   0,   7, 135, 253, 186,  12,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  85, 252, 223,   0,   0,   0,   0,
          0,   0,   0,   0,   7, 131, 252, 225,  71,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  85, 252, 145,   0,   0,   0,   0,
          0,   0,   0,  48, 165, 252, 173,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  86, 253, 225,   0,   0,   0,   0,
          0,   0, 114, 238, 253, 162,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  85, 252, 249, 146,  48,  29,  85,
        178, 225, 253, 223, 167,  56,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  85, 252, 252, 252, 229, 215, 252,
        252, 252, 196, 130,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,  28, 199, 252, 252, 253, 252, 252,
        233, 145,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,  25, 128, 252, 253, 252, 141,
         37,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   

In [ ]:
x_train = x_train.reshape(x_train.shape[0], -1)
x_test = x_test.reshape(x_test.shape[0], -1)
#reshaping sisnce input layer neded to be in 1d
#so we changed from 2d to 1d

In [ ]:
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [ ]:
x_train[1] #comparewoth the earlier x[1] which was in 2d

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  51, 159, 253,
       159,  50,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  48, 238,
       252, 252, 252, 237,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [ ]:
#to change dtatype

In [ ]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')


In [ ]:
x_train = x_train / 255
x_test = x_test / 255
#ask chatgpt y
x_train[0]


array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [ ]:
num_classes=10

y_train[0]







5

In [ ]:


[0,0,0,0,0,1,0,0,0,0]



[0, 0, 0, 0, 0, 1, 0, 0, 0, 0]

In [ ]:
y_train = y_train.flatten()  # Ensure y_train is 1D
y_train = keras.utils.to_categorical(y_train, num_classes)



y_test=keras.utils.to_categorical(y_test,num_classes)


In [ ]:
print(y_train.shape)


(60000, 10)


In [ ]:
print(y_test.shape)

(10000, 10)


In [ ]:
model=Sequential()
model.add(Dense(64,activation='relu',input_shape=(784,)))  # Hidden Layer 1
model.add(Dense(64,activation='relu'))  # Hidden Layer 2
model.add(Dense(10,activation='softmax'))  # Output Layer


In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 64)                  │          50,240 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 64)                  │           4,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 10)                  │             650 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 55,050 (215.04 KB)

 Trainable params: 55,050 (215.04 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Every neuron passes its connection to the next neuron.
# Initially, there were 64 neurons in the hidden layers, while the output layer has only 10 neurons.
# Parameters (params) refer to weights and biases.

In [ ]:
# Compiling the model with categorical cross-entropy loss for multi-class classification.
# Using RMSprop optimizer with a learning rate of 0.001.
# Tracking accuracy as the evaluation metric.

model.compile(loss='categorical_crossentropy',
              optimizer=RMSprop(learning_rate=0.001),
              metrics=['accuracy'])

# Setting batch size to 32 and training for 30 epochs.
batch_size = 32
epochs = 30

# Training the model using training data.
# Using a batch size of 32 and validating on test data after each epoch.
history = model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs,
                    verbose=1, validation_data=(x_test, y_test))


Epoch 1/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.8657 - loss: 0.4712 - val_accuracy: 0.9532 - val_loss: 0.1563
Epoch 2/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.9600 - loss: 0.1322 - val_accuracy: 0.9644 - val_loss: 0.1118
Epoch 3/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9715 - loss: 0.0950 - val_accuracy: 0.9691 - val_loss: 0.0985
Epoch 4/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9785 - loss: 0.0747 - val_accuracy: 0.9713 - val_loss: 0.0932
Epoch 5/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9817 - loss: 0.0628 - val_accuracy: 0.9736 - val_loss: 0.0984
Epoch 6/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9833 - loss: 0.0552 - val_accuracy: 0.9750 - val_loss: 0.0884
Epoch 7/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9864 - loss: 0.0469 - val_accuracy: 0.9766 - val_loss: 0.0966
Epoch 8/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9863 - loss: 0.0463 